name: build

on:
  push:
    branches:
    - master
jobs:
   build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    steps:
      - uses: actions/checkout@v2
      - name: gcc
        run: gcc -Wall -Werror -Wextra -I ../src ../src/*.c tests_libft.c
        
