name: build

on:
  push:
    branches:
    - master
jobs:
   build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v4.1.4
      - name: make
        run: make
        
