name: valgrind

on:
  push:
    branches:
    - master
jobs:
   test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    steps:
      - name: Install dependencies
        run: |
          apt-get install valgrind
      - uses: actions/checkout@v2
      - name: make leakfull
        run: make leakfull
